### ISSUE TITLE
Error that prevented startup

### ISSUE THREAD

**Issue by enrinor** [ErikGartner/vtesdb#14]
=> Started proxy.
=> Meteor 1.6.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Errors prevented startup:

   While minifying app stylesheet:
   module.js:536:15: Cannot find module 'autoprefixer'
   at Function.Module._resolveFilename (module.js:536:15)
   at Function.resolve (internal/module.js:18:19)
   at Object.require (C:\tools\isobuild\bundler.js:1873:34)
   at packages/minifier-postcss/plugin/minify-css.js:52:37
   at Array.forEach (<anonymous>)
   at getPostCSSPlugins (packages/minifier-postcss/plugin/minify-css.js:51:43)
   at packages/minifier-postcss/plugin/minify-css.js:155:36
   at Array.map (<anonymous>)
   at mergeCss (packages/minifier-postcss/plugin/minify-css.js:139:23)
   at CssToolsMinifier.processFilesForBundle (packages/minifier-postcss/plugin/minify-css.js:109:18)

=> Your application has errors. Waiting for file change.

**Comment by ErikGartner** [comment]
This is because you haven't installed the npm dependencies.

 See the updated readme with added installation instructions.
